In [2]:
%pip install -r ../requirements.txt

Requirement already satisfied: sqlalchemy in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 1)) (2.0.41)
Requirement already satisfied: ace_tools==0.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 2)) (0.0)
Requirement already satisfied: appnope==0.1.4 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 3)) (0.1.4)
Requirement already satisfied: asttokens==3.0.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 4)) (3.0.0)
Requirement already satisfied: babel==2.17.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 5)) (2.17.0)
Requirement already satisfied: blessed==1.21.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 6)) (1.21.0)
Requirement already satisfied: blessings==1.7 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 7)) (1.7)
Requirement already satisfied: bpython==0.24 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 8)) (0.24)
Requirement already satisfied: certifi==2025.8.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 9)) (2025.8.3)
Requirement already satisfied: charset-normalizer==3.4.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 10)) (3.4.3)
Requirement already satisfied: colour==0.1.5 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 11)) (0.1.5)
Requirement already satisfied: comm==0.2.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 12)) (0.2.3)
Requirement already satisfied: contourpy==1.3.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 13)) (1.3.2)
Requirement already satisfied: curtsies==0.4.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 14)) (0.4.2)
Requirement already satisfied: cwcwidth==0.1.10 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 15)) (0.1.10)
Requirement already satisfied: cycler==0.12.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 16)) (0.12.1)
Requirement already satisfied: debugpy==1.8.15 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 17)) (1.8.15)
Requirement already satisfied: decorator==5.2.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 18)) (5.2.1)
Requirement already satisfied: dotenv==0.9.9 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 19)) (0.9.9)
Requirement already satisfied: dtreeviz==2.2.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 20)) (2.2.2)
Requirement already satisfied: executing==2.2.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 21)) (2.2.0)
Requirement already satisfied: fonttools==4.59.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 22)) (4.59.0)
Requirement already satisfied: graphviz==0.21 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 23)) (0.21)
Requirement already satisfied: greenlet==3.2.4 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 24)) (3.2.4)
Requirement already satisfied: idna==3.10 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 25)) (3.10)
Requirement already satisfied: iniconfig==2.1.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 26)) (2.1.0)
Requirement already satisfied: ipykernel==6.30.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 27)) (6.30.0)
Requirement already satisfied: ipython==9.4.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 28)) (9.4.0)
Requirement already satisfied: ipython-genutils==0.2.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 29)) (0.2.0)
Requirement already satisfied: ipython-sql==0.5.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 31)) (0.5.0)
Requirement already satisfied: jedi==0.19.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 32)) (0.19.2)
Requirement already satisfied: joblib==1.5.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 33)) (1.5.1)
Requirement already satisfied: jupyter_client==8.6.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 34)) (8.6.3)
Requirement already satisfied: jupyter_core==5.8.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 35)) (5.8.1)
Requirement already satisfied: kiwisolver==1.4.8 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 36)) (1.4.8)
Requirement already satisfied: load-dotenv==0.1.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 37)) (0.1.0)
Requirement already satisfied: matplotlib==3.10.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 38)) (3.10.3)
Requirement already satisfied: matplotlib-inline==0.1.7 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 39)) (0.1.7)
Requirement already satisfied: mysql-connector-python==9.4.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 40)) (9.4.0)
Requirement already satisfied: nest-asyncio==1.6.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 41)) (1.6.0)
Requirement already satisfied: numpy==2.3.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 42)) (2.3.2)
Requirement already satisfied: packaging==25.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 43)) (25.0)
Requirement already satisfied: pandas==2.3.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 44)) (2.3.1)
Requirement already satisfied: parso==0.8.4 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 45)) (0.8.4)
Requirement already satisfied: pexpect==4.9.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 46)) (4.9.0)
Requirement already satisfied: pillow==11.3.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 47)) (11.3.0)
Requirement already satisfied: pip==25.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 48)) (25.2)
Requirement already satisfied: platformdirs==4.3.8 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 49)) (4.3.8)
Requirement already satisfied: pluggy==1.6.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 50)) (1.6.0)
Requirement already satisfied: prettytable==3.16.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 51)) (3.16.0)
Requirement already satisfied: prompt_toolkit==3.0.51 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 52)) (3.0.51)
Requirement already satisfied: psutil==7.0.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 53)) (7.0.0)
Requirement already satisfied: ptyprocess==0.7.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 54)) (0.7.0)
Requirement already satisfied: pure_eval==0.2.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 55)) (0.2.3)
Requirement already satisfied: Pygments==2.19.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 56)) (2.19.2)
Requirement already satisfied: PyMySQL==1.1.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 57)) (1.1.1)
Requirement already satisfied: pyparsing==3.2.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 58)) (3.2.3)
Requirement already satisfied: pytest==8.4.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 59)) (8.4.1)
Requirement already satisfied: python-dateutil==2.9.0.post0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 60)) (2.9.0.post0)
Requirement already satisfied: python-dotenv==1.1.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 61)) (1.1.1)
Requirement already satisfied: pytz==2025.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 62)) (2025.2)
Requirement already satisfied: pyxdg==0.28 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 63)) (0.28)
Requirement already satisfied: pyzmq==27.0.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 64)) (27.0.0)
Requirement already satisfied: requests==2.32.5 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 65)) (2.32.5)
Requirement already satisfied: scikit-learn==1.7.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 66)) (1.7.1)
Requirement already satisfied: scipy==1.16.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 67)) (1.16.0)
Requirement already satisfied: seaborn==0.13.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 68)) (0.13.2)
Requirement already satisfied: six==1.17.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 69)) (1.17.0)
Requirement already satisfied: sqlparse==0.5.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 71)) (0.5.3)
Requirement already satisfied: stack-data==0.6.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 72)) (0.6.3)
Requirement already satisfied: threadpoolctl==3.6.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 73)) (3.6.0)
Requirement already satisfied: tkcalendar==1.6.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 74)) (1.6.1)
Requirement already satisfied: tornado==6.5.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 75)) (6.5.1)
Requirement already satisfied: traitlets==5.14.3 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 76)) (5.14.3)
Requirement already satisfied: typing_extensions==4.14.1 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 77)) (4.14.1)
Requirement already satisfied: tzdata==2025.2 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 78)) (2025.2)
Requirement already satisfied: urllib3==2.5.0 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 79)) (2.5.0)
Requirement already satisfied: wcwidth==0.2.13 in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from -r ../requirements.txt (line 80)) (0.2.13)
Requirement already satisfied: ipython-pygments-lexers in /Users/chibangnguyen/.pyenv/versions/3.13.5/lib/python3.13/site-packages (from ipython==9.4.0->-r ../requirements.txt (line 28)) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

# Setting

In [3]:
from dotenv import load_dotenv
import os

load_dotenv()

user = os.getenv("DB_USER")
password = os.getenv("DB_PASS")
host = os.getenv("DB_HOST")
dbname = os.getenv("DB_NAME_SCHOOL")

from sqlalchemy import create_engine
engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}/{dbname}", connect_args={'init_command': 'SET time_zone="+07:00"'})

# Data

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sqlalchemy import create_engine, text

In [5]:
query = """select MAMH, DIEM_HE4, TINCHI
        from  MONHOC natural join KETQUA
        where  TENMH not like '%Giáo dục thể chất%' and TENMH not like '%Bóng đá%'
        """
df = pd.read_sql(query, engine)

In [6]:
df.head()

     MAMH  DIEM_HE4  TINCHI
0  801043       2.0       4
1  801046       1.0       4
2  801047       1.0       4
3  801145       2.0       3
4  801351       4.0       2

In [7]:
df1 = pd.DataFrame({'MAMH': ["841047", # Công nghệ phần mền
                             "848028", # Phân tích xử lý ảnh
                             "tanh123", # Tiếng Anh 123
                             ], 
                    'DIEM_HE4': [4.0,
                                 4.0,
                                 4.0,
                                 ], 
                    'TINCHI': [4,
                               4,
                               10,
                               ]})
# df1 = pd.DataFrame()
df1.head()

      MAMH  DIEM_HE4  TINCHI
0   841047       4.0       4
1   848028       4.0       4
2  tanh123       4.0      10

In [8]:
union_all = pd.concat([df, df1], ignore_index=True)

In [9]:
from sqlalchemy import text

def update_caithien(mamh, diem):
    with engine.begin() as conn:  # begin() auto-commits or rolls back
        conn.execute(
            text("""
                UPDATE `KETQUA`
                SET `DIEM_HE4` = :diem
                WHERE `MAMH` = ":mamh"
            """),
            {"diem": diem, "mamh": mamh}
        )

In [10]:
# update_caithien(801401, 0.0) # diem goc mon dstt
# update_caithien(841403, 1.0) # diem goc mon ctrr
update_caithien(801401, 4.0) # diem cai thien mon dstt
update_caithien(841403, 4.0) # diem cai thien mon ctrr

In [11]:
gpa = (union_all['DIEM_HE4'] * union_all['TINCHI']).sum() / union_all['TINCHI'].sum()
print(f"GPA: {gpa:.2f}")

GPA: 3.02