In [1]:
%pip install mysql-connector-python pandas
%pip install SQLAlchemy
%pip install load_dotenv
%pip install pandas
%pip install matplotlib
%pip install ipython-sql
%pip install scipy
%pip install numpy

Requirement already satisfied: mysql-connector-python in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (9.3.0)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.1.3)
Requirement already satisfied: numpy<2,>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: SQLAlchemy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.0.41)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from SQLAlchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: load_dotenv in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.1.0)
Requirement already satisfied: python-dotenv in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from load_dotenv) (1.1.1)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.1.3)
Requirement already satisfied: numpy<2,>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.8.2)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (4.45.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy<2,>=1.21 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from matplotlib) (2.8.2)
Requirement already satisfied: six>=1.5 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: ipython-sql in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.5.0)
Requirement already satisfied: prettytable in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython-sql) (3.16.0)
Requirement already satisfied: ipython in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from ipython-sql) (8.18.1)
Requirement already satisfied: sqlalchemy>=2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython-sql) (2.0.41)
Requirement already satisfied: sqlparse in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython-sql) (0.4.4)
Requirement already satisfied: six in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.14.1)
Requirement already satisfied: decorator in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from ipython->ipython-sql) (0.19.1)
Requirement already satisfied: matplotlib-inline in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from ipython->ipython-sql) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from ipython->ipython-sql) (2.17.2)
Requirement already satisfied: stack-data in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from ipython->ipython-sql) (0.6.3)
Requirement already satisfied: traitlets>=5 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from ipython->ipython-sql) (5.13.0)
Requirement already satisfied: pexpect>4.3 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: wcwidth in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.12)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: ptyprocess>=0.5 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from stack-data->ipython->ipython-sql) (2.0.1)
Requirement already satisfied: asttokens>=2.1.0 in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from stack-data->ipython->ipython-sql) (2.4.1)
Requirement already satisfied: pure-eval in /Users/chibangnguyen/Library/Python/3.12/lib/python/site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.11.4)
Requirement already satisfied: numpy<1.28.0,>=1.21.6 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scipy) (1.26.4)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import sys
sys.path.append('data_analyst/package')

# Set up database

In [3]:
from dotenv import load_dotenv
import os

load_dotenv()

user = os.getenv("DB_USER")
password = os.getenv("DB_PASS")
host = os.getenv("DB_HOST")
dbname = os.getenv("DB_NAME")

from sqlalchemy import create_engine
engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}/{dbname}", connect_args={'init_command': 'SET time_zone="+07:00"'})

In [4]:
import pandas as pd
from scipy.stats import binom
import matplotlib.pyplot as plt

In [5]:
from package import bayes

In [6]:
bayes.run_bayes(30)

,ACTIVITY_ID,ACT_NAME,Total,Learning,Overview,Practice
0,1,Statistics for Business & Economics,7.5,0.0,7.5,0.0
1,2,[RESEARCH] Location-Scheduling Problem,7.5,0.0,7.5,0.0
2,5,THE KEY TO IELTS SUCCESS - Pauline Cullen,7.5,7.5,0.0,0.0
3,28,Computer Organization and Design - DAVID A. PA...,7.5,7.5,0.0,0.0

In [8]:
bayes.get_view(1)

,ACTIVITY_ID,ACT_NAME,PRIOR_PROB,POSTERIOR_PROB_LEARNING,POSTERIOR_PROB_OVERVIEW,POSTERIOR_PROB_PRACTICE
0,1,Statistics for Business & Economics,0.2,0.0,1.0,0.0
1,2,[RESEARCH] Location-Scheduling Problem,0.2,0.0,1.0,0.0
2,5,THE KEY TO IELTS SUCCESS - Pauline Cullen,0.2,1.0,0.0,0.0
3,28,Computer Organization and Design - DAVID A. PA...,0.2,1.0,0.0,0.0